name: Build And Push Docker Image

on:
  push:
    branches:
      - 'master'
      - 'develop'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  schedule:
    # 参考 https://jasonet.co/posts/scheduled-actions/
    # note: 这里是GMT时间，北京时间减去八小时即可。如北京时间 22:30 => GMT 14:30
    # minute hour day month dayOfWeek
    - cron: '00 12 * * *' # GMT 14:00 => 北京时间 22:00
    #- cron: '30 16 * * *' # GMT 16:30（前一天） => 北京时间 00:30
  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/whyour/qinglong/archive/refs/heads/${{ github.ref_name }}.zip
          unzip *.zip
          cp ./qinglong-${{ github.ref_name }}/* .
          cp ./qinglong-${{ github.ref_name }}/.* .

      - name: build front and back
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build:front
          pnpm build:back

      - name: copy to static repo
        env:
          GITHUB_REPO: github.com/${{ github.repository_owner }}/qinglong-static
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          mkdir -p tmp
          cd ./tmp
          cp -rf ../static/* ./
          git init -b ${GITHUB_BRANCH} && git add .
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty -m "copy static at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.API_TOKEN }}@${GITHUB_REPO}.git" ${GITHUB_BRANCH}:${GITHUB_BRANCH}
  build:
    needs: build-static

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H%M%S')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
# 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构
          network: host
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
# 镜像推送时间
          push: ${{ github.event_name != 'pull_request' }}
# 给清单打上多个标签
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/qinglong:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/qinglong:${{ steps.date.outputs.today }}
